---
title: "Supplement TE: Teachers’ experience with epilepsy"
date: today
published-title: "last modified"
author:
    name: Pawel R. Kulawiak
    orcid: 0000-0001-5939-4380
    email: kulawiak@uni-potsdam.de
format:
  html:
    title-block-banner: true
    number-sections: true
    embed-resources: true
    page-layout: full
    toc: true
    toc-location: body
    code-fold: true
    html-table-processing: none
execute: 
  warning: false
  message: false
bibliography: packages.bib
appendix-style: none
notice: |
  @R-base, @R-tidyverse, @R-gt, @R-readxl, @R-gtExtras, @R-devtools, @R-knitr
---

# R packages

```{r}
library(tidyverse)
library(gt)
library(readxl)
library(gtExtras)
library(devtools)
library(knitr)
write_bib(file = "packages.bib")
```

# Data import and manipulation

```{r}
DATA <- read_xlsx("SURVEY_DATA.xlsx")

DATA <-
  DATA %>%
  select(-where( ~ all(is.na(.)))) %>%
  filter(`teilnahme[teilnahme]` == "Y")

DATA <-
  DATA[9:81] %>%
  mutate(NA_CHECK = rowSums(!is.na(.))) %>%
  filter(NA_CHECK > 0) %>%
  filter(AB7 == 0) %>% # exclude special education schools
  mutate(SED_INC = case_when(AB10 == 0 & AB11 == 0 ~ 0,
                             AB10 == 1 & AB11 == 0 ~ 1,
                             AB10 == 0 & AB11 == 1 ~ 2,
                             AB10 == 1 & is.na(AB11) ~ 1,
                             is.na(AB10) & AB11 == 1 ~ 2,
                             AB10 == 1 & AB11 == 1 ~ 3,
                             is.na(AB10) & is.na(AB11) ~ NA,
                             AB10 == 0 & is.na(AB11) ~ NA,
                             is.na(AB10) & AB11 == 0 ~ NA)) %>%
  rename_with(~ stringr::str_replace_all(., "\\[", "_") %>%
                 stringr::str_replace_all(., "\\]", ""))
```

# Custom functions

```{r}
describe <-
  function(var) {
    DATA %>%
      group_by({{var}}) %>%
      reframe(n = n()) %>%
      rename(V1 = names(.)[1]) %>% 
      mutate(percent = (n / sum(n))) %>%
      mutate(INDEX = n) %>%
      mutate(percent = (percent*100) %>% round(1)) %>%
      relocate(percent, .after = last_col()) %>%
      mutate(n = NULL)
  }
```

# Table: Teachers' experience with epilepsy

```{r}
NAMES <-
  c("very high", "somewhat high", "somewhat low", "very low", "missing value",
    "yes",
    "yes", "missing value",
    "yes",
    "yes", "missing value",
    "yes")

rbind(
  describe(AB0 %>% factor(levels = 4:1)), # prior knowledge about epilepsy
  describe(AB1) %>% slice(-1), # currently teaching students with epilepsy
  describe(AB2) %>% slice(-1), # previously taught students with epilepsy
  describe(AB3) %>% slice(-1), # witnessed a student having an epileptic seizure
  describe(AB4) %>% slice(-1), # witnessed a person having an epileptic seizure
  describe(AB5) %>% slice(-1)  # have or have had regular contact with people with epilepsy
) %>%
  mutate(V1 = NAMES) %>% 
  gt() %>%
  gt_plt_bar_pct(column = percent,
                 scaled = T,
                 labels = TRUE,
                 fill = "black",
                 width = 100,
                 height = 20,
                 label_cutoff = 0.7,
                 font_size = "12px") %>%
  cols_align("left") %>%
  cols_label(V1 = "",
             INDEX = md("***N***"),
             percent = md("***%***")) %>%
  tab_row_group(label = md("*have or have had regular contact with PWE (y/n)*"), rows = 12) %>%
  tab_row_group(label = md("*witnessed a person having an epileptic seizure (y/n)*"), rows = 10:11) %>%
  tab_row_group(label = md("*witnessed a student having an epileptic seizure (y/n)*"), rows = 9) %>%
  tab_row_group(label = md("*previously taught students with epilepsy (y/n)*"), rows = 7:8) %>%
  tab_row_group(label = md("*currently teaching students with epilepsy (y/n)*"), rows = 6) %>%
  tab_row_group(label = md("*prior knowledge about epilepsy (self-rating)*"), rows = 1:5) %>%
  tab_style(style = list(cell_text(indent = pct(10))), locations = cells_body(columns = V1)) %>% 
  tab_options(column_labels.background.color = "gray95",
              footnotes.background.color = "gray95") %>%
  tab_style(style = cell_fill(color = "gray95"), locations = cells_row_groups(groups = everything())) %>%
  tab_footnote(md("*PWE = People with epilepsy*")) %>%
  cols_align(align = "center", columns = starts_with("percent")) %>%
  cols_align(align = "right", columns = starts_with("INDEX")) %>%
  tab_options(table.align = "left")

```

# R session info

```{r collapse=TRUE}
session_info()
```

# References 
